export const dataOptions = {
  especialidades: {
    maquina_A: [
      {
        id: 100,
        idFamilia: 10,
        sku: "30207",
        familia: "Especialidades",
        kg_lote: null,
        rack: "-",
        no_rack: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "-",
      },
      {
        id: 101,
        idFamilia: 10,
        sku: "30221",
        familia: "Especialidades",
        kg_lote: null,
        rack: "-",
        no_rack: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "-",
      },
    ],
    maquina_B: [
      {
        id: 200,
        idFamilia: 10,
        sku: "30238",
        familia: "Especialidades",
        kg_lote: null,
        rack: "-",
        no_rack: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "-",
      },
    ],
    maquina_C: [
      {
        id: 300,
        idFamilia: 10,
        sku: "30245",
        familia: "Especialidades",
        kg_lote: null,
        rack: "-",
        no_rack: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "-",
      },
    ],
  },
  formulacion: {
    celda_1: [
      {
        id: 1,
        idFamilia: 1,
        sku: "X072",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Lunch",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "EMUL + CYD + SALM",
        emulsion: "PASTA + SALM + CYD",
        tipo_emulsion: "EMUL",
      },
      {
        id: 2,
        idFamilia: 1,
        sku: "X576",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Lunch",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 3,
        idFamilia: 2,
        sku: "53612",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 4,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 5,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 6,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 7,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 8,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
    ],
    celda_2: [
      {
        id: 9,
        idFamilia: 1,
        sku: "CF0232",
        familia: "Jamones Granel",
        kg_lote: 3575,
        rack: "Pinic 5",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "EMUL + CYD + SALM",
        emulsion: "PASTA + SALM + CYD",
        tipo_emulsion: "EMUL",
      },
      {
        id: 10,
        idFamilia: 1,
        sku: "X438",
        familia: "Jamones Granel",
        kg_lote: 1070,
        rack: "Lunch",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 11,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Rebanados",
        kg_lote: 1070,
        rack: "Bala",
        no_rack: 3.5,
        kg_barra: 9.7,
        no_barras: 110,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
    ],
  },
  salchichas_granel: {
    maquina_A: [
      {
        id: 12,
        idFamilia: 3,
        sku: "X971",
        familia: "Salchichas Granel",
        kg_lote: 1070,
        rack: "Lunch",
        no_rack: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "-",
        emulsion: "-",
        tipo_emulsion: "-",
      },
      {
        id: 13,
        idFamilia: 3,
        sku: "81128",
        familia: "Salchichas Granel",
        kg_lote: 2200,
        rack: "-",
        no_rack: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "-",
        emulsion: "-",
        tipo_emulsion: "-",
      },
    ],
    maquina_B: [
      {
        id: 14,
        idFamilia: 3,
        sku: "81135",
        familia: "Salchichas Granel",
        kg_lote: null,
        rack: "-",
        no_rack: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "-",
        emulsion: "-",
        tipo_emulsion: "-",
      },
    ],
  },
};

export const dataTimings = [
  "ingredientes_secos",
  "salmuerizador",
  "corte_deshuese_frescos",
  "emulsiones",
  "mezcladora",
  "embutido",
  "cocimiento",
  "enfriamiento",
  "desmolde",
  "atemperado",
  "rebanado",
  "entrega",
  "te_ingredientes_salmuera",
  "te_salmuera_mezclado",
  "te_emulsiones_mezclado",
  "te_cyd_emulsiones",
  "te_cyd_mezclado",
  "te_mezclado_embutido",
  "te_embutido_cocimiento",
  "te_cocimiento_enfriamiento",
  "te_enfriamiento_desmolde",
  "te_desmolde_atemperado",
  "te_atemperado_rebanado",
];

export const dataFamily = [
  "Jamones Granel",
  "Jamones Rebanados",
  "Jamones Pastel",
  "Salchichas Granel",
  "Salchichas para Asar",
  "Salchichas Especialidades",
  "Especialidades",
];
