export const history = [
  {
    sku: "X282",
    plan: null,
    lunes: null,
    martes: null,
    miercoles: null,
    jueves: null,
    viernes: 2976,
    sabado: 5952,
    total: 8928,
    dif: null,
  },
  {
    sku: "10360",
    plan: null,
    lunes: null,
    martes: null,
    miercoles: null,
    jueves: null,
    viernes: 2650,
    sabado: null,
    total: 2650,
    dif: null,
  },
  {
    sku: "X010",
    plan: null,
    lunes: null,
    martes: null,
    miercoles: null,
    jueves: null,
    viernes: 3230,
    sabado: null,
    total: 3230,
    dif: null,
  },
];
